version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: adotepet
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3100:3100"
    environment:
      DATABASE_URL: postgres://postgres:123@postgres:5432/adotepet
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: >
      sh -c "npm install &&
             npx prisma generate &&
             npx prisma migrate deploy &&
             npm run dev"

volumes:
  postgres_data:
